# mkdocs.yml

site_name: Tutorial Ros
site_author: Joao Vitor

theme:
  name: readthedocs # Você queria este tema!
  logo: 'img/logo.png'

# Removemos 'palette' e 'features', pois não são do tema 'readthedocs'

nav:
  - 'Início': 'index.md'
  - 'Máquina Virtual': 'Mv.md'
  - 'Robô Pioneer' : 'Pioneer3dx.md'
  - 'Lidar slamtec': 'lidar.md'
  - 'Braço Robótico': 'Braco.md'

# Diz ao MkDocs para carregar nossos arquivos personalizados
extra_css:
  - css/extra.css

extra_javascript:
  - js/copy-code.js